#!/usr/bin/env python3
"""Make a generated mesh's faces point outward.

**The defect.** Our meshes ship with *inconsistent* face winding, and often with the
majority of faces pointing inward -- a Flicker run measured a **negative volume** of
-0.02369. glTF materials are double-sided by default, so a textured preview looks fine and
the defect is invisible. Turn backface culling on -- which is what SceneKit, RealityKit and
every game engine do -- and the asset is hollow: you look straight through the chest and
see the inside of the far side.

Both assets generated by the official TRELLIS.2 demo are winding-consistent with positive
volume. Ours were not. This is ours to fix.

**Why it matters beyond looking wrong.** It corrupted our own diagnostics for weeks. Every
"see-through hole" measured on a culled render, and the tear metric this repo gated on,
were substantially counting *flipped faces* rather than missing geometry -- which is why
repairs kept failing to move the number, and why "recalculate normals" kept appearing to
fix assets that were never torn.

**The fix, in two steps and both necessary:**

1. ``fix_normals()`` makes the winding *consistent* -- but consistency alone can leave the
   whole mesh uniformly inside-out, which is exactly what happened here.
2. If the signed volume is then negative, ``invert()`` flips it to face outward.

Geometry, UVs and textures are untouched; only face winding changes.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def needs_inverting(volume: float) -> bool:
    """A negative signed volume means the surface is inside-out.

    Split out so the decision is testable without a mesh: it is the step that
    ``fix_normals()`` alone does not perform, and forgetting it leaves an asset that is
    consistently wrong instead of inconsistently wrong.
    """
    return volume < 0.0


def repair(mesh) -> dict:
    """Make winding consistent and outward. Returns what changed."""
    before_consistent = bool(mesh.is_winding_consistent)
    before_volume = float(mesh.volume)

    mesh.fix_normals()
    inverted = needs_inverting(float(mesh.volume))
    if inverted:
        mesh.invert()

    return {
        "was_consistent": before_consistent,
        "was_volume": before_volume,
        "inverted": inverted,
        "now_consistent": bool(mesh.is_winding_consistent),
        "now_volume": float(mesh.volume),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("asset", type=Path)
    parser.add_argument("output", type=Path, nargs="?", help="defaults to in-place")
    args = parser.parse_args()

    import trimesh

    destination = args.output or args.asset
    mesh = trimesh.load(str(args.asset), force="mesh", process=False)
    report = repair(mesh)
    destination.parent.mkdir(parents=True, exist_ok=True)
    mesh.export(str(destination))

    print(
        f"winding: consistent {report['was_consistent']} -> {report['now_consistent']}, "
        f"volume {report['was_volume']:+.5f} -> {report['now_volume']:+.5f}"
        f"{' (inverted)' if report['inverted'] else ''}"
    )
    print(f"wrote {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
